

import java.util.List;
import java.util.ArrayList;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class Test extends javax.swing.JFrame {
    
      List<String[]> questions = new ArrayList<>();
    int currentIndex = 0;
    List<String> studentAnswers = new ArrayList<>();
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Test.class.getName());

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        applyDesign();
        // disable exam, admin and result tabs at start
jTabbedPane1.setEnabledAt(2, false); // Admin tab index 2
jTabbedPane1.setEnabledAt(3, false); // Exam tab index 3
jTabbedPane1.setEnabledAt(4, false); // Result tab index 4
   this.setSize(600, 480);
    this.setLocationRelativeTo(null); // center on screen
    this.setTitle("Online Exam Portal");
        
        buttonGroup2.add(optA);
        buttonGroup2.add(optB);
        buttonGroup2.add(optC);
        buttonGroup2.add(optD);
           loadQuestionsFromDB(); // ADD THIS
           showQuestion(); 
           
    }
    
    private void loadQuestionsFromDB() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection cn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/OnlineExam", "root", "MySql@123"
        );
        PreparedStatement ps = cn.prepareStatement("SELECT * FROM questions");
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String[] q = new String[6];
            q[0] = rs.getString("question");
            q[1] = rs.getString("option_a");
            q[2] = rs.getString("option_b");
            q[3] = rs.getString("option_c");
            q[4] = rs.getString("option_d");
            q[5] = rs.getString("correct_option");
            questions.add(q);
        }
        System.out.println("Questions loaded: " + questions.size());
        cn.close();

    } catch (Exception e) {
        System.out.println(e);
    }
}

private void showQuestion() {
    if (currentIndex >= questions.size()) {
        submitExam();
        return;
    }

    String[] q = questions.get(currentIndex);

    questionNumber.setText("Question " + (currentIndex + 1) + " of " + questions.size());
    questionLabel.setText(q[0]);
    optA.setText("A.  " + q[1]);
    optB.setText("B.  " + q[2]);
    optC.setText("C.  " + q[3]);
    optD.setText("D.  " + q[4]);

    buttonGroup2.clearSelection();
}


private void submitExam() {
   
    

    // calculate score
    int score = 0;
    for (int i = 0; i < studentAnswers.size(); i++) {
        if (studentAnswers.get(i).equals(questions.get(i)[5])) {
            score++;
        }
    }

    int total = questions.size();
    int wrong = studentAnswers.size() - score;

    // show result
    JOptionPane.showMessageDialog(this,
        "Exam Finished!\n\n" +
        "Total Questions : " + total + "\n" +
        "Correct Answers : " + score + "\n" +
        "Wrong Answers   : " + wrong + "\n\n" +
        "Your Score      : " + score + " / " + total
    );

    // switch to result tab automatically
    jTabbedPane1.setSelectedIndex(4);

    // show score in result tab
    jLabel18.setText("Your Score: " + score + " / " + total);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_email = new javax.swing.JTextField();
        l_password = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r_name = new javax.swing.JTextField();
        r_email = new javax.swing.JTextField();
        r_password = new javax.swing.JTextField();
        r_city = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        q_question = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        q_a = new javax.swing.JTextField();
        q_b = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        q_c = new javax.swing.JTextField();
        q_d = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        q_correctAns = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        optD = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        questionNumber = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("LogIn");

        jLabel7.setText("Enter your Email");

        jLabel8.setText("Enter your password");

        jButton2.setText("LogIn");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jLabel6))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("LogIn", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Student Registration");

        jLabel2.setText("Enter your name");

        jLabel3.setText("Enter your Email");

        jLabel4.setText("Enter your password");

        jLabel5.setText("City");

        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(r_city, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(r_password)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(r_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(r_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(r_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(r_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(r_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(r_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Registration", jPanel2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Admin Panel - Add Questions");

        jLabel10.setText("Question");

        jLabel11.setText("Option A");

        jLabel12.setText("Option B");

        jLabel13.setText("Option C");

        jLabel14.setText("Option D");

        jLabel15.setText("Correct Answer");

        q_correctAns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jButton3.setText("Add Question");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(q_question, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(q_correctAns, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q_a, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q_c, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(q_b, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(q_d))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q_correctAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel3);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setText("Exam");

        optA.setText("jRadioButton1");

        optB.setText("jRadioButton2");

        optC.setText("jRadioButton3");
        optC.addActionListener(this::optCActionPerformed);

        optD.setText("jRadioButton4");

        nextBtn.setText("Next Question");
        nextBtn.addActionListener(this::nextBtnActionPerformed);

        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        questionLabel.setText("jLabel19");

        questionNumber.setText("jLabel20");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(optA)
                    .addComponent(optB)
                    .addComponent(optD)
                    .addComponent(optC)
                    .addComponent(questionLabel)
                    .addComponent(questionNumber))
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(nextBtn)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(questionNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionLabel)
                .addGap(18, 18, 18)
                .addComponent(optA)
                .addGap(18, 18, 18)
                .addComponent(optB)
                .addGap(18, 18, 18)
                .addComponent(optC)
                .addGap(18, 18, 18)
                .addComponent(optD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextBtn)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exam ", jPanel4);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setText("Your Result will be shown Here");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel18)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel18)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Result", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String rname = r_name.getText();
            String remail = r_email.getText();
            String rpassword = r_password.getText();
            String rcity = r_city.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection cn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/OnlineExam","root","MySql@123");
            
            PreparedStatement ps;
            ps = cn.prepareStatement("insert into students(name,email,password,city) values(?,?,?,?) ");
            ps.setString(1,rname);
            ps.setString(2,remail);
            ps.setString(3,rpassword);
            ps.setString(4,rcity);
            
            boolean b = ps.execute();
            if(b==false){
                JOptionPane.showMessageDialog(rootPane,"Registered Successfully");
            }
            cn.close();
            }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
    String lemail    = l_email.getText();
    String lpassword = l_password.getText();

    // Basic validation
    if (lemail.isEmpty() || lpassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    // Check admin first
    if (lemail.equals("admin") && lpassword.equals("admin123")) {
        jTabbedPane1.setEnabledAt(2, true);  // enable Admin tab
        jTabbedPane1.setSelectedIndex(2);    // jump to Admin tab
        return; // stop here
    }

    // Student login — check database
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection cn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/OnlineExam", "root", "MySql@123"
    );
    PreparedStatement ps = cn.prepareStatement(
        "SELECT * FROM students WHERE email = ? AND password = ?"
    );
    ps.setString(1, lemail);
    ps.setString(2, lpassword);

    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        JOptionPane.showMessageDialog(this, "Login Successful!");
        jTabbedPane1.setEnabledAt(3, true);  // enable Exam tab
        jTabbedPane1.setEnabledAt(4, true);  // enable Result tab
        jTabbedPane1.setSelectedIndex(3);    // jump to Exam tab
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Email or Password!");
    }

    cn.close();

} catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
             String question = q_question.getText();
        String A = q_a.getText();
        String B = q_b.getText();
        String C = q_c.getText();
        String D = q_d.getText();
        String correct = q_correctAns.getSelectedItem().toString();
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/OnlineExam","root","MySql@123");
        
        PreparedStatement ps = cn.prepareStatement("insert into questions( question, option_a, option_b, option_c, option_d,correct_option) values(?,?,?,?,?,?)");
        ps.setString(1, question);
        ps.setString(2, A);
        ps.setString(3, B);
        ps.setString(4, C);
        ps.setString(5, D);
        ps.setString(6, correct);
        
        int rows = ps.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Question Added Successfully!");
            // Clear fields after adding
            q_question.setText("");
            q_a.setText("");
            q_b.setText("");
            q_c.setText("");
            q_d.setText("");
            q_correctAns.setSelectedIndex(0);
        }
        else{
            System.out.println("Question not inserted!!");
        }

        cn.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void optCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCActionPerformed
    
    
       
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
       try{
            {
    String selected = "";

    if (optA.isSelected()) selected = "A";
    else if (optB.isSelected()) selected = "B";
    else if (optC.isSelected()) selected = "C";
    else if (optD.isSelected()) selected = "D";
    else {
        JOptionPane.showMessageDialog(this, "Please select an answer!");
        return;
    }

    studentAnswers.add(selected);
    currentIndex++;
    showQuestion();
}
       }
       catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_nextBtnActionPerformed
   
    
    
    
    private void applyDesign() {

    // ── Colors ──
    java.awt.Color navy      = new java.awt.Color(28, 57, 100);
    java.awt.Color medBlue   = new java.awt.Color(52, 101, 164);
    java.awt.Color lightBlue = new java.awt.Color(235, 242, 251);
    java.awt.Color darkGrey  = new java.awt.Color(52, 52, 52);
    java.awt.Color midGrey   = new java.awt.Color(120, 120, 120);
    java.awt.Color lightGrey = new java.awt.Color(245, 245, 247);
    java.awt.Color white     = java.awt.Color.WHITE;
    java.awt.Color border    = new java.awt.Color(210, 210, 215);

    // ── Fonts ──
    java.awt.Font heading = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22);
    java.awt.Font subhead = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);
    java.awt.Font normal  = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
    java.awt.Font small   = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12);

    // ── Border for all text fields ──
    javax.swing.border.Border fieldBorder =
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(border, 1),
            javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10)
        );

    // ── Window background ──
    getContentPane().setBackground(lightGrey);
    jTabbedPane1.setBackground(lightGrey);
    jTabbedPane1.setFont(subhead);

    // ─────────────────────────────
    // LOGIN TAB
    // ─────────────────────────────
    jPanel1.setBackground(lightGrey);

    // heading
    jLabel6.setFont(heading);
    jLabel6.setForeground(navy);

    // labels
    jLabel7.setFont(normal);
    jLabel7.setForeground(darkGrey);
    jLabel8.setFont(normal);
    jLabel8.setForeground(darkGrey);

    // fields
    l_email.setFont(normal);
    l_email.setBackground(white);
    l_email.setBorder(fieldBorder);
    l_email.setPreferredSize(new java.awt.Dimension(200, 35));

    l_password.setFont(normal);
    l_password.setBackground(white);
    l_password.setBorder(fieldBorder);
    l_password.setPreferredSize(new java.awt.Dimension(200, 35));
    l_email.setPreferredSize(new java.awt.Dimension(220, 36));
l_password.setPreferredSize(new java.awt.Dimension(220, 36));

    // button
    jButton2.setBackground(navy);
    jButton2.setForeground(white);
    jButton2.setFont(subhead);
    jButton2.setBorderPainted(false);
    jButton2.setFocusPainted(false);
    jButton2.setOpaque(true);
    jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton2.setPreferredSize(new java.awt.Dimension(160, 38));

    // ─────────────────────────────
    // REGISTRATION TAB
    // ─────────────────────────────
    jPanel2.setBackground(lightGrey);

    jLabel1.setFont(heading);
    jLabel1.setForeground(navy);

    jLabel2.setFont(normal); jLabel2.setForeground(darkGrey);
    jLabel3.setFont(normal); jLabel3.setForeground(darkGrey);
    jLabel4.setFont(normal); jLabel4.setForeground(darkGrey);
    jLabel5.setFont(normal); jLabel5.setForeground(darkGrey);

    r_name.setFont(normal);     r_name.setBackground(white);
    r_name.setBorder(fieldBorder);
    r_name.setPreferredSize(new java.awt.Dimension(200, 35));

    r_email.setFont(normal);    r_email.setBackground(white);
    r_email.setBorder(fieldBorder);
    r_email.setPreferredSize(new java.awt.Dimension(200, 35));

    r_password.setFont(normal); r_password.setBackground(white);
    r_password.setBorder(fieldBorder);
    r_password.setPreferredSize(new java.awt.Dimension(200, 35));

    r_city.setFont(normal);     r_city.setBackground(white);
    r_city.setBorder(fieldBorder);
    r_city.setPreferredSize(new java.awt.Dimension(200, 35));

    jButton1.setBackground(navy);
    jButton1.setForeground(white);
    jButton1.setFont(subhead);
    jButton1.setBorderPainted(false);
    jButton1.setFocusPainted(false);
    jButton1.setOpaque(true);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.setPreferredSize(new java.awt.Dimension(160, 38));

    // ─────────────────────────────
    // ADMIN TAB
    // ─────────────────────────────
    jPanel3.setBackground(lightGrey);

    jLabel9.setFont(heading);  jLabel9.setForeground(navy);
    jLabel10.setFont(normal);  jLabel10.setForeground(darkGrey);
    jLabel11.setFont(normal);  jLabel11.setForeground(darkGrey);
    jLabel12.setFont(normal);  jLabel12.setForeground(darkGrey);
    jLabel13.setFont(normal);  jLabel13.setForeground(darkGrey);
    jLabel14.setFont(normal);  jLabel14.setForeground(darkGrey);
    jLabel15.setFont(normal);  jLabel15.setForeground(darkGrey);

    q_question.setFont(normal); q_question.setBackground(white);
    q_question.setBorder(fieldBorder);
    q_question.setPreferredSize(new java.awt.Dimension(300, 35));

    q_a.setFont(normal); q_a.setBackground(white); q_a.setBorder(fieldBorder);
    q_b.setFont(normal); q_b.setBackground(white); q_b.setBorder(fieldBorder);
    q_c.setFont(normal); q_c.setBackground(white); q_c.setBorder(fieldBorder);
    q_d.setFont(normal); q_d.setBackground(white); q_d.setBorder(fieldBorder);

    q_correctAns.setFont(normal);
    q_correctAns.setBackground(white);

    jButton3.setBackground(medBlue);
    jButton3.setForeground(white);
    jButton3.setFont(subhead);
    jButton3.setBorderPainted(false);
    jButton3.setFocusPainted(false);
    jButton3.setOpaque(true);
    jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    // ─────────────────────────────
    // EXAM TAB
    // ─────────────────────────────
    jPanel4.setBackground(lightGrey);

    jLabel16.setFont(heading);
    jLabel16.setForeground(navy);

    

    questionNumber.setFont(small);
    questionNumber.setForeground(midGrey);

    // KEY FIX — allows question text to wrap multiple lines
    questionLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    questionLabel.setPreferredSize(new java.awt.Dimension(500, 80));
questionLabel.setMaximumSize(new java.awt.Dimension(500, 80));
    questionLabel.setForeground(navy);
    questionLabel.setBackground(lightBlue);
    questionLabel.setOpaque(true);
    questionLabel.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, medBlue),
            javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
        )
    );
    questionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    questionLabel.setPreferredSize(new java.awt.Dimension(350, 70));

    
    
    // radio buttons
    optA.setFont(normal); optA.setBackground(lightGrey); optA.setForeground(darkGrey);
    optB.setFont(normal); optB.setBackground(lightGrey); optB.setForeground(darkGrey);
    optC.setFont(normal); optC.setBackground(lightGrey); optC.setForeground(darkGrey);
    optD.setFont(normal); optD.setBackground(lightGrey); optD.setForeground(darkGrey);

    // next button
    nextBtn.setBackground(navy);
    nextBtn.setForeground(white);
    nextBtn.setFont(subhead);
    nextBtn.setBorderPainted(false);
    nextBtn.setFocusPainted(false);
    nextBtn.setOpaque(true);
    nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    nextBtn.setPreferredSize(new java.awt.Dimension(140, 38));

    // ─────────────────────────────
    // DISABLE TABS UNTIL LOGIN
    // ─────────────────────────────
    jTabbedPane1.setEnabledAt(2, false);
    jTabbedPane1.setEnabledAt(3, false);
    jTabbedPane1.setEnabledAt(4, false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Test().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField l_email;
    private javax.swing.JTextField l_password;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JRadioButton optD;
    private javax.swing.JTextField q_a;
    private javax.swing.JTextField q_b;
    private javax.swing.JTextField q_c;
    private javax.swing.JComboBox<String> q_correctAns;
    private javax.swing.JTextField q_d;
    private javax.swing.JTextField q_question;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel questionNumber;
    private javax.swing.JTextField r_city;
    private javax.swing.JTextField r_email;
    private javax.swing.JTextField r_name;
    private javax.swing.JTextField r_password;
    // End of variables declaration//GEN-END:variables
}
